version: '3.8'
services:
  postgres:
    build:
      context: services/postgres
      dockerfile: Dockerfile.development
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=SMT
      - POSTGRES_PASSWORD=2222
    volumes:
      - "db-data:/var/lib/postgresql/data"
volumes:
  db-data: